modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="dascore" 
version="${file.jarVersion}" 
displayName="DasCore" 
logoFile="examplemod.png" 
credits="YouTube and Stackexchange" 
authors="uDasBoot" 
description='''
Some type of mod created by uDasBoot
TBD
'''

[[dependencies.dascore]]
    modId="forge"
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.dascore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
